spring:
  application:
    name: clearing-house-service

  datasource:
    url: jdbc:h2:mem:clearinghouse;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  cloud:
    function:
      definition: validation;novation-split;novation-persist;notification-enrich;notification-email
    stream:
      bindings:
        validation-in-0:
          destination: incoming-trades
        validation-out-0:
          destination: validated-trades
        novation-split-in-0:
          destination: validated-trades
        novation-split-out-0:
          destination: novated-trades
        novation-persist-in-0:
          destination: novated-trades
          consumer:
            max-attempts: 1
        notification-enrich-in-0:
          destination: persisted-trades
        notification-enrich-out-0:
          destination: novated-trade-confirmations
        notification-email-in-0:
          destination: novated-trade-confirmations
        notification-email-out-0:
          destination: email-notifications

currency-api:
  url: http://localhost:8081

logging:
  level:
    com.clearinghouse: DEBUG

server:
  port: 8080
